version: "3.8"

services:
  mysqldb:
    image: 'mysql@sha256:eb00f19a38312b85bfb7195eead2d07d35279f2a6a61b3dc994094dcefa57986'
    container_name: db
    ports:
      - '3307:3306'
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_USER=${MYSQL_DB_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
    networks:
      - appsnetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minidock:2
    container_name: app
    depends_on:
      - mysqldb
    ports:
      - '8080:8080'
    env_file: .env
    environment:
      - MYSQL_DB_HOST_NAME=mysqldb
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - MYSQL_DB_USERNAME=${MYSQL_DB_USERNAME}
    networks:
      - appsnetwork

networks:
  appsnetwork: